# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='question',
            field=models.TextField(),
        ),
    ]
